import Header from "@/components/Header";
import "./globals.css";
import { session } from "@/Session";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//   // @ts-ignore


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = window.localStorage.getItem("user")
   console.log(session)
  return (
    <html lang="en">
      <body>
      
        {/* {!false ? (
          <Authentication />
        ) : (
          <>
            <Header />
            {children}
          </>
        )} */}
        <Header />
        {children}
      </body>
    </html>
  );
}
