import Authentication from "@/components/Auth/Authentication";
import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* {!session ? (
          <Authentication />
        ) : (
          <>
            <Header />
            {children}
          </>
        )} */}
        {children}
      </body>
    </html>
  );
}
