import Authentication from "@/components/auth/Authentication";
import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//   // @ts-ignore
//   const session = JSON.parse(localStorage.getItem("user") || ""); 


// console.log(session)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  

  return (
    <html lang="en">
      <body>
        {/* {!false ? (
          <Authentication />
        ) : (
          <>
            <Header />
            {children}
          </>
        )} */}
        <Header />
        {children}
      </body>
    </html>
  );
}
